name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.7", "pypy3.8", "pypy3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libxml2
        run: |
          sudo apt-get update
          sudo apt-get install libxml2 libxml2-dev libxslt1-dev
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          source env/bin/activate
          pytest
