name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libxml2
        run: |
          sudo apt-get update
          sudo apt-get install libxml2 libxml2-dev libxslt1-dev
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --user
      - name: Run tests with pytest
        run: pytest